// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"time"
)

type User struct {
	ID             string    `json:"id"`
	Email          string    `json:"email"`
	Nickname       string    `json:"nickname"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	PasswordDigest string    `json:"password_digest"`
}
