// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package dbgen

import (
	"context"
)

const userFindAll = `-- name: UserFindAll :many
SELECT
    id, email, nickname, created_at, updated_at, password_digest
FROM
    users
`

func (q *Queries) UserFindAll(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, userFindAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Nickname,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordDigest,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userFindByEmail = `-- name: UserFindByEmail :one
SELECT
    id, email, nickname, created_at, updated_at, password_digest
FROM
    users
WHERE
    email = ?
`

func (q *Queries) UserFindByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, userFindByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordDigest,
	)
	return i, err
}

const userFindById = `-- name: UserFindById :one
SELECT
    id, email, nickname, created_at, updated_at, password_digest
FROM
    users
WHERE
    id = ?
`

func (q *Queries) UserFindById(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, userFindById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Nickname,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordDigest,
	)
	return i, err
}

const userInsert = `-- name: UserInsert :exec
INSERT INTO
    users (
    id,
    email,
    nickname,
    password_digest,
    created_at,
    updated_at
)
VALUES (
    ?,
    ?,
    ?,
    ?,
    NOW(),
    NOW()
)
`

type UserInsertParams struct {
	ID             string `json:"id"`
	Email          string `json:"email"`
	Nickname       string `json:"nickname"`
	PasswordDigest string `json:"password_digest"`
}

func (q *Queries) UserInsert(ctx context.Context, arg UserInsertParams) error {
	_, err := q.db.ExecContext(ctx, userInsert,
		arg.ID,
		arg.Email,
		arg.Nickname,
		arg.PasswordDigest,
	)
	return err
}

const userUpsert = `-- name: UserUpsert :exec
INSERT INTO
    users (
    id,
    email,
    nickname,
    password_digest,
    created_at,
    updated_at
)
VALUES (
    ?,
    ?,
    ?,
    ?,
    NOW(),
    NOW()
) ON DUPLICATE KEY
UPDATE
    email = ?,
    nickname = ?,
    password_digest = ?,
    updated_at = NOW()
`

type UserUpsertParams struct {
	ID             string `json:"id"`
	Email          string `json:"email"`
	Nickname       string `json:"nickname"`
	PasswordDigest string `json:"password_digest"`
}

func (q *Queries) UserUpsert(ctx context.Context, arg UserUpsertParams) error {
	_, err := q.db.ExecContext(ctx, userUpsert,
		arg.ID,
		arg.Email,
		arg.Nickname,
		arg.PasswordDigest,
		arg.Email,
		arg.Nickname,
		arg.PasswordDigest,
	)
	return err
}
