volumes:
  db-store:

networks:
  echo-practice-network:

services:
  db:
    container_name: db
    image: mysql:8.0.35-debian
    volumes:
      - db-store:/var/lib/mysql
    networks:
      - echo-practice-network
    environment:
      MYSQL_DATABASE: echo_practice
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      LANG: C.UTF-8
    command: --collation-server=utf8mb4_general_ci
    platform: linux/x86_64

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./build/Dockerfile
    networks:
      - echo-practice-network
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    entrypoint: ["go", "run", "./cmd/main.go"]
    depends_on:
      - db