volumes:
  db-store:

networks:
  echo-practice-network:

services:
  db:
    container_name: db
    image: mysql:8.0.35-debian
    restart: on-failure
    volumes:
      - db-store:/var/lib/mysql
    networks:
      - echo-practice-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: echo_practice
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      LANG: C.UTF-8
    command: --collation-server=utf8mb4_general_ci
    platform: linux/x86_64

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - echo-practice-network
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    entrypoint: ["sh", "-c", "go run ./cmd/main.go"]
    depends_on:
      - db

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - echo-practice-network
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    entrypoint: ["sh", "-c", "pnpm install && pnpm dev"]
    depends_on:
      - app
